modLoader="javafml"
license="LGPLv3"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Trinsdar/GT-Foods/issues"
[[mods]]
modId="gt_foods"
version="${version}"
displayName="GT Foods"
displayURL="https://github.com/Trinsdar/GT-4-Reimagined"
credits="Greg for the original foods from gt6" #optional
authors="Trinsdar" #optional
description='''
Adds more food to minecraft, inspired by gt5 and 6 foods.
'''
[[dependencies.gt_foods]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.gt_foods]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.gt_foods]]
    modId="antimatter"
    mandatory=false
    versionRange="[0.0.4,)"
    ordering="AFTER"
    side="BOTH"